config/routes.rb
require 'sidekiq/web'
class SubdomainConstraint
  def self.matches?(request)
    # plug in exclusions model here
    restricted_subdomains = []
    !restricted_subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  get 'cookies', to: 'cookies#index'
  get 'cookies/fetch', to: 'cookies#fetch'
  # analytics dashboard
  get 'dashboard', controller: 'comfy/admin/dashboard'
  get 'dashboard/sessions/:ahoy_visit_id', to: 'comfy/admin/dashboard#visit', as: :dashboard_visits
  get 'dashboard/events/:ahoy_event_type', to: 'comfy/admin/dashboard#events_detail', as: :dashboard_events
  get 'dashboard/events_list', to: 'comfy/admin/dashboard#events_list', as: :dashboard_events_list
  delete 'dashboard/events/:ahoy_event_type/destroy_event', to: 'comfy/admin/dashboard#destroy_event', as: :dashboard_destroy_event
  delete 'dashboard/events/:ahoy_event_type/destroy_visits', to: 'comfy/admin/dashboard#destroy_visits', as: :dashboard_destroy_visits

  post 'import_api_namespace', to: 'comfy/admin/api_namespaces#import_as_json', as: :import_as_json_api_namespaces

  get 'v2/dashboard', to: 'comfy/admin/v2/dashboard#dashboard'

  get 'sales_collateral_dashboard', to: 'comfy/admin/sales_collateral#dashboard'

  resources :sales_collateral, controller: 'comfy/admin/sales_collateral' do
    member do
      get 'export'
    end
  end

  # video calling, lock down new/create actions-- and allow public show action
  get 'rooms', to: 'comfy/admin/rooms#new'
  post 'rooms', to: 'comfy/admin/rooms#create'
  resources :rooms, only: [:show]
  
  resources :signup_wizard
  resources :signin_wizard
  constraints SubdomainConstraint do
    devise_for :users, controllers: {
      confirmations: 'users/confirmations',
      #omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks',
      invitations: 'users/invitations'
    }
  end

  resource :mailbox, only: [:show], controller: 'mailbox/mailbox' do
    resources :message_threads, controller: 'mailbox/message_threads' do
      resources :messages
      member do
        post 'send_message'
        patch 'add_categories'
      end
    end
    resources :email_templates, controller: 'mailbox/email_templates' do
      member do
        post 'test_send'
      end
    end
  end

  # email tracking
  get 'email_tracking/open', to: 'mailbox/tracking#open'

  # calendar / meetings functionality
  resources :calendars, controller: 'comfy/admin/calendars'
  resources :meetings

  resource :web_settings, controller: 'comfy/admin/web_settings', only: [:edit, :update]
  resources :users, controller: 'comfy/admin/users', as: :admin_users, except: [:create, :show] do
    collection do
      post 'invite'
    end
    member do
      get 'edit/sessions/:ahoy_visit_id', to: 'comfy/admin/dashboard#visit', as: :user_sessions_visit
    end
  end

  # api admin
  resources :api_namespaces, controller: 'comfy/admin/api_namespaces' do
    member do
      post 'duplicate_with_associations'
      post 'duplicate_without_associations'
      get 'export_with_associations_as_json'
      get 'export_without_associations_as_json'
      patch 'social_share_metadata'
      patch 'analytics_metadata'
      patch 'api_action_workflow'
      patch 'settings', to: 'comfy/admin/api_namespaces#update_settings'
    end

    resources :resources, except: [:index], controller: 'comfy/admin/api_resources'
    resources :api_clients, controller: 'comfy/admin/api_clients'
    resources :external_api_clients, controller: 'comfy/admin/external_api_clients' do
      member do
        get 'start'
        get 'stop'
        get 'clear_errors'
        get 'clear_state'
      end
    end
    resources :api_forms, controller: 'comfy/admin/api_forms', only: [:edit, :update]

    resources :resource, controller: 'resource', only: [:create]

    resources :api_actions, controller: 'comfy/admin/api_actions', only: [:index, :show, :new] do
      collection do
        get 'action_workflow'
      end
    end

    member do
      post 'discard_failed_api_actions'
      post 'rerun_failed_api_actions'
      get 'export'
      get 'export_api_resources'
    end
  end

  resources :api_keys, controller: 'comfy/admin/api_keys'
  resources :non_primitive_properties, controller: 'comfy/admin/non_primitive_properties', only: [:new]

  # system admin panel login
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_global_admin_session
    get 'otp/', to: 'users/sessions#two_factor'
    delete 'global_login', to: 'users/sessions#destroy'
    get 'resend_otp', to: "users/registrations#resend_otp"
    get '/users/sign_in/otp' => 'users/otp/sessions#new'
    post '/users/sign_in/otp' => 'users/otp/sessions#create'
  end
  # system admin panel authentication (ensure public schema as well)
  get 'sysadmin', to: 'admin/subdomain_requests#index'
  namespace :admin do
    authenticate :user, lambda { |u| u.global_admin? } do
      mount Sidekiq::Web => '/sidekiq'
      mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
      get 'web_console', to: 'web_console#index'
      mount Blazer::Engine, at: "blazer"
    end
    resources :subdomain_requests, except: [:new, :create] do
      member do
        get 'approve'
        get 'disapprove'
      end
    end
    resources :subdomains
  end

  
  namespace 'api' do
    get '/resources', to: 'resources#index', as: :show_resources
    scope ':version' do
      scope ':api_namespace' do
        get '/', to: 'resource#index'
        get '/show/:api_resource_id', to: 'resource#show', as: :show_resource
        get '/describe', to: 'resource#describe'
        post '/query', to: 'resource#query'
        post '/', to: 'resource#create', as: :create_resource
        patch '/edit/:api_resource_id', to: 'resource#update', as: :update_resource
        delete '/destroy/:api_resource_id', to: 'resource#destroy', as: :destroy_resource
        post '/:external_api_client/webhook', to: 'external_api_clients#webhook', as: :external_api_client_webhook
      end
    end
  end

  # ahoy analytics
  mount Ahoy::Engine => "/ahoy", as: :my_ahoy

  # to query CMS pages
  post '/query', to: 'search#query'
  # to query the rest of the system
  post "/graphql", to: "graphql#execute"

  # catch web client route before it gets hijacked by the server
  if RUBY_VERSION != "3.0.0"
    mount_ember_app :client, to: "/app"
  end

  comfy_route :cms_admin, path: "/admin"
  comfy_route :blog, path: "blog"
  comfy_route :blog_admin, path: "admin"
  mount SimpleDiscussion::Engine => "/forum"
  # cms comes last because its a catch all
  comfy_route :cms, path: "/"

  root to: 'content#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/comfy/admin/api_forms_controller.rb
class Comfy::Admin::ApiFormsController < Comfy::Admin::Cms::BaseController
  before_action :set_api_namespace
  before_action :ensure_authority_for_full_access_for_api_form_only_in_api, only: %i[ edit update ]

  before_action :set_api_form, only: %i[show edit update]

  def edit
  end

  def update
    respond_to do |format|
      if @api_form.update(api_form_params)
        format.html { redirect_to api_namespace_path(id: @api_namespace.slug), notice: "Api Form was successfully updated." }
        format.json { render :show, status: :ok, location: @api_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api_form.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_api_namespace
    @api_namespace = ApiNamespace.find_by(id: params[:api_namespace_id])
  end

  def set_api_form
    @api_form = ApiForm.find(params[:id])
  end

  def api_form_params
    params.require(:api_form).permit(:api_namespace_id, :show_recaptcha, :show_recaptcha_v3, :submit_button_label, :title, :success_message, :failure_message, properties: {}).merge({api_namespace_id: @api_namespace.id})
  end
end

app/helpers/api_forms_helper.rb
module ApiFormsHelper
  def render_form(id, options = {})
    # usage in cms  {{ cms:helper render_form, 1 }} here 1 is the id
    # usage in rails = render_form @api_form.id
    @api_form = ApiForm.find_by(id: id)
    if @api_form
      @api_namespace = @api_form.api_namespace
      data = options['data'] || {}

      data["violet-track-form-submit"] = "true" unless data["violet-track-form-submit"].present?
      render partial: 'comfy/admin/api_forms/render', locals: { data: data }
    end
  end

  def map_form_field(form, key, value, form_properties)
    case value.class.to_s
    when 'Array'
      if form_properties[key]['input_type'] == 'radio'
        render partial: 'comfy/admin/api_forms/radio', locals: {form: form, key: key, value: value, form_properties: form_properties}
      else
        if form_properties[key]['select_type'] == 'multi' || !value.present?
          form.select key, options_for_select(value), { multiple: true, include_blank: true}, {class: "form-control array_select", name: "data[properties][#{key}][]", required: form_properties.dig(key, 'required') == '1', default_value: form_properties.dig(key, 'prepopulated_options').present? ? form_properties.dig(key, 'prepopulated_options').to_s : "[]" , placeholder: form_properties.dig(key, 'placeholder'), 'data-tags': !value.present? }
        else
          form.select key, options_for_select(value, form_properties[key]['prepopulated_options_single']), { include_blank: form_properties[key]['placeholder'] }, {class: "form-control", name: "data[properties][#{key}", required: form_properties[key]['required'] == '1' }
        end
      end
    when 'TrueClass', 'FalseClass'
      options = {required: form_properties[key]['required'] == '1', type: 'checkbox'}
      options[:checked] = value if form_properties[key]['prepopulate'] == '1'
      options[:value] = form_properties[key]['prepopulate'] == '1' ? value : 'false'
      form.check_box key, options,  'true', 'false'
    when 'Hash'
      render partial: 'comfy/admin/api_forms/jsoneditor', locals: {form: form, key: key, value: value} 
    else
      options = { placeholder: value, required: form_properties[key]['required'] == '1', class: 'form-control'}
      options[:type] = form_properties[key]['type_validation'] if form_properties[key]['type_validation'].present?
      options[:pattern] = form_properties[key]['pattern'] if form_properties[key]['type_validation'] == ApiForm::INPUT_TYPE_MAPPING[:regex_pattern] && form_properties[key]['pattern'].present?
      options[:value] = value if form_properties[key]['prepopulate'] == '1'
      if form_properties[key]['field_type'] == 'textarea'
        form.text_area key, options
      else
        form.text_field key, options
      end
    end
  end

  def map_non_primitive_data_type(form, type, form_properties = {}, is_edit = false)
    key = form.object.label.to_sym
    case type
    when 'file'
      options = { required:  form_properties&.dig(key, 'required') == '1', class: 'form-control', type: 'file', direct_upload: true, onchange: "previewFile(event, '#{key.to_s.parameterize.underscore}_preview')" }
      form.file_field :attachment, options
    when 'richtext'
      options = { placeholder:  form_properties&.dig(key, 'placeholder'), required:  form_properties&.dig(key, 'required') == '1' }
      options[:value] =  form_properties&.dig(key, 'prepopulate') == '1' || is_edit ? form.object.content : ''
      form.rich_text_area :content, options
    end
  end

  def map_form_field_type(data_type)
    case data_type
    when 'String'
      'Text field'
    when 'Integer'
      'Number field'
    when 'Array'
      'Multiselect'
    when 'TrueClass', 'FalseClass'
      'Checkbox'
    when 'Hash'
      'Json input'
    else
      'String'
    end
  end
end
  

app/views/comfy/admin/api_forms/_form.html.haml
- action = @api_form.persisted? ? :put : :post
- path = @api_form.persisted? ? api_namespace_api_form_path(api_namespace_id: @api_form.api_namespace.id, id: @api_form.id) : api_namespace_api_forms_path(api_namespace_id: @api_form.api_namespace.id)
- properties = @api_form.properties

= form_for @api_form, url: path, method: action do |f|
  - if @api_form.errors.any?
    #error_explanation
      %h2= "#{pluralize(@api_form.errors.count, "error")} prohibited this api_form from being saved:"
      %ul
        - @api_form.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .my-5
    %h3.my-2 
      Messages
    .form-group
      = f.label :success_message
      = f.text_area :success_message, data: {'cms-cm-mode' => 'text/html'}
    .form-group
      = f.label :failure_message
      = f.text_area :failure_message, data: {'cms-cm-mode' => 'text/html'}

  %h3 Fields
  .row
    = f.fields_for :properties do |p|
      - @api_namespace.properties.each do |key, value|
        .col-12.col-md-4.mb-4
          .card.p-3
            %h4.mb-3
              = key
            .form-group.d-flex.align-items-baseline
              .mr-4
                = 'Data type:'
              %div
                = value.class.to_s
            .form-group.d-flex.align-items-baseline
              .mr-4
                = 'Input Field Type: '
              %div
                = map_form_field_type(value.class.to_s)
            = p.fields_for key do |a|
              .row.mb-3.align-items-end
                .form-group.col-12
                  = a.label :label, 'Label:', class: 'mr-4'
                  = a.text_field :label, class: 'form-control', value: properties[key]["label"]
                - unless value.class.to_s == 'Array'
                  .form-group.col-12
                    = a.label :prepopulate, 'Prepopulate:', class: 'mr-4'
                    = a.check_box :prepopulate, checked: properties[key]["prepopulate"] == '1'
                - if value.class.to_s == 'String' || value.class.to_s == 'Integer' 
                  .form-group.col-12
                    = a.label :field_type, 'Field type', class: 'mr-4'
                    = a.select :field_type, options_for_select(['input', 'textarea'], properties[key]["field_type"] || 'input'), {}, {class: 'form-control' }
                  .form-group.col-12
                    = a.label :type_validation, 'Type validation', class: 'mr-4'
                    = a.select :type_validation, options_for_select(ApiForm::INPUT_TYPE_MAPPING, properties[key]["type_validation"] || 'text'), {}, {class: 'form-control', onchange: "toggleRegex(this , '#{key}_regex')" }
                  .form-group.col-12{style: "#{'display: none' unless properties[key]["type_validation"] == ApiForm::INPUT_TYPE_MAPPING[:regex_pattern] }", id: "#{key}_regex"}
                    = a.label :pattern, 'REGEX Pattern', class: 'mr-4'
                    = a.text_field :pattern, class: 'form-control', value: properties[key]["pattern"], placeholder: '[A-Za-z]{3}'
                    .mt-2.form-control-sm.pl-0
                      Regex editor:
                      = link_to 'Rubular', "https://rubular.com/", {target: '_blank'}
                - if value.class.to_s == 'Array'
                  .form-group.col-12
                    = a.label :input_type, 'Input Type:', class: 'mr-4'
                    = a.select :input_type, options_for_select(['select', 'radio'], properties[key]["input_type"]), {}, {class: "form-control"}
                  .form-group.col-12
                    = a.label :select_type, 'Select Type:', class: 'mr-4'
                    = a.select :select_type, options_for_select(['single', 'multi'], properties[key]["select_type"]), {}, {class: "form-control", onchange: "toggleOptionField(this, '#{key}')"}
                  .form-group.col-12{style: "#{'display: none' unless properties[key]['select_type'] == 'multi'}", id: "#{key}_prepopulate_multi"}
                    = a.label :prepopulated_options, 'Prepopulate Options:', class: 'mr-4'
                    = a.select key, options_for_select(value), { multiple: true }, {class: "form-control array_select", name: "api_form[properties][#{key}][prepopulated_options][]", default_value: properties[key]["prepopulated_options"] ? properties[key]["prepopulated_options"].to_s : [].to_s}
                  .form-group.col-12{style: "#{'display: none' if properties[key]['select_type'] == 'multi'}", id: "#{key}_prepopulate_single"}
                    = a.label :prepopulated_options_single, 'Prepopulate Option:', class: 'mr-4'
                    = a.select :prepopulated_options_single, options_for_select(value, properties[key]['prepopulated_options_single']), { include_blank: true }, {class: "form-control"}
                  .form-group.col-12
                    = a.label :placeholder, 'Placeholder:', class: 'mr-4'
                    = a.text_field :placeholder, class: 'form-control', value: properties[key]["placeholder"]

                .form-group.col-12
                  = a.label :required, 'Required:', class: 'mr-4'
                  = a.check_box :required, checked: properties[key]["required"] == "1"

                .form-group.col-12
                  = a.label :renderable, 'Renderable', class: 'mr-4'
                  = a.check_box :renderable, checked: @api_form.is_field_renderable?(key)
      
      - @api_namespace.non_primitive_properties.each do |prop|
        .col-12.col-md-4.mb-4
          .card.p-3
            %h4.mb-3
              = prop.label
            .form-group.d-flex.align-items-baseline
              .mr-4
                = 'Data type:'
              %div
                = prop.field_type
            = p.fields_for prop.label do |a|
              .row.mb-3.align-items-end
                .form-group.col-12
                  = a.label :prepopulate, 'Prepopulate:', class: 'mr-4'
                  = a.check_box :prepopulate, checked: properties.dig(prop.label, "prepopulate") == '1'
                .form-group.col-12
                  = a.label :required, 'Required:', class: 'mr-4'
                  = a.check_box :required, checked: properties.dig(prop.label, "required") == '1'
                .form-group.col-12
                  = a.label :placeholder, 'Placeholder:', class: 'mr-4'
                  = a.text_field :placeholder,class: 'form-control', value: properties.dig(prop.label, "placeholder")

        
  %h3.mt-4
    Button
  .form-group
    = f.label :submit_button_label
    = f.text_field :submit_button_label, class: 'form-control'

  %h3.mt-4
    Recaptcha Type
    %span{ style: "font-size: small;"}
      ( *Select only one )

  .form-group.mb-0
    = f.label :show_recaptcha, 'Show recaptcha v2'
    = f.check_box :show_recaptcha, data: { group: 'recaptcha-type' }

  .form-group.mt-0
    = f.label :show_recaptcha_v3
    = f.check_box :show_recaptcha_v3, data: { group: 'recaptcha-type' }
    
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

:javascript
  $(document).ready( function() {
    $(".array_select").select2({
      multiple: true,
      required: false,
      tags: true,
      placeholder: "Leave empty if you don't want to prepopulate"
    })
    $('.array_select').each(function() {
      $(this).val(JSON.parse($(this).attr('default_value'))).change();
    })

    toggleRecaptchaTypeChecboxes();
  });


  function toggleRegex(select, regexFieldId) {
    var type = $(select).val();
    if (type === "#{ApiForm::INPUT_TYPE_MAPPING[:regex_pattern]}") {
      $('#' + regexFieldId).show();
    } else {
      $('#' + regexFieldId).hide();
    }
  }

  function toggleOptionField(select, key) {
    var type = $(select).val();
    console.log(type, key)
    if (type == 'single') {
      $('#' + key + '_prepopulate_single').show();
      $('#' + key +  '_prepopulate_multi').hide();
    }

    if (type == 'multi') {
      $('#' + key + '_prepopulate_single').hide();
      $('#' + key +  '_prepopulate_multi').show();
    }
  }

  function toggleRecaptchaTypeChecboxes() {
    $("input[type='checkbox'][data-group='recaptcha-type']").on('click', function() {
      if (this.checked) {
        const currentElement = this;

        $("input[type='checkbox'][data-group='recaptcha-type']").each(function() {
          if (this != currentElement) {
            this.checked = false;
          }
        })
      }
    })
  }

app/views/comfy/admin/api_forms/_jsoneditor.haml
.jsoneditor{id: "#{key}-editor"}
= hidden_field_tag "data[properties][#{key}]", value.to_json

:javascript
  // create the editor
  #{key}_initJsonEditor();

  function #{key}_initJsonEditor() {
    const container = document.getElementById("#{key}-editor")
    const options = {onChange: () => { setFields() } }
    const editor = new JSONEditor(container, options)

    // set json
    const initialJson = {}
    editor.set(initialJson)

    let existingValue = $("#data_properties_#{key}").val()

    if (existingValue) {
        let json = JSON.parse(existingValue)
        editor.set(json)
    } else {
        setFields()
    }

    function setFields() {
        str = JSON.stringify(editor.get())
        $("#data_properties_#{key}").val(str)
    }

    // get json
    const updatedJson = editor.get()
  }

app/views/comfy/admin/api_forms/_radio.html.haml
.fields
  - value.each do |item|
    %label.checkbox-container
      %span.ml-2 
        = item
      - if form_properties.dig(key, 'select_type') == 'multi' 
        = form.check_box(key, { :multiple => true, checked: form_properties.dig(key,'prepopulated_options')&.include?(item), class: "#{key}-checkbox", required: form_properties.dig(key, 'required') == '1' }, item, nil)
      - else
        = form.radio_button key, item , checked: form_properties.dig(key,'prepopulated_options_single') == item, required: form_properties.dig(key, 'required') == '1'
      %span.radio-selection

- if form_properties.dig(key, 'select_type') == 'multi' && form_properties.dig(key, 'required') == '1' 
  :javascript
    requireCheckbox("#{key}-checkbox")

app/views/comfy/admin/api_forms/_render.haml
%link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.0.0/jsoneditor.css", :integrity => "sha512-Mfp9P5Ln+lF/PmixCJBHUNHXoBKJwKY2i7oZ29iu/mnN47puo0TH/ORb3vgrdkyuBkLaDytv80480FNZxllpyQ==", :referrerpolicy => "no-referrer", :rel => "stylesheet"}/
%script{:crossorigin => "anonymous", :integrity => "sha512-xEv8uIENS4DGY7Ml/Cv6+sbcPXiRAguIgU8Sv0FCUUdrNC7aRhWbOglm7lnzhnA3spqCr8DnTMTMNFW4jhM8gA==", :referrerpolicy => "no-referrer", :src => "https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.0.0/jsoneditor.js"}
- properties = @api_namespace.properties.symbolize_keys
- form_properties = @api_form.properties.symbolize_keys

-# There must be recaptcha keys set if recaptcha v2/v3 is used in the api_form.
- recaptcha_keys_set = @api_form.show_recaptcha && Recaptcha.configuration.site_key.present? && Recaptcha.configuration.secret_key.present?
- recaptcha_keys_set = @api_form.show_recaptcha_v3 && ENV['RECAPTCHA_SITE_KEY_V3'].present? && ENV['RECAPTCHA_SECRET_KEY_V3'].present? unless recaptcha_keys_set

- if (@api_form.show_recaptcha.blank? && @api_form.show_recaptcha_v3.blank?) || recaptcha_keys_set
  = form_for :data, url: api_namespace_resource_index_path(api_namespace_id: @api_namespace.id), method: :post, html: {class: 'violet-cta-form', 'data-type': 'json', multipart: true, id: "api_form_#{@api_form.object_id}", onsubmit: 'disableForm(this); return checkRequiredRichTextFields()'}, data: { turbo: false, remote: true, slug: @api_namespace.slug }.merge(data) do |f|
    = hidden_field_tag :form_id, @api_form.object_id
    .form-group
      - properties.each do |key, value|
        = f.fields_for :properties do |fff|
          - if @api_form.is_field_renderable?(key)
            .form-group{class: "vr-#{key}"}
              = fff.label key, form_properties[key]["label"]
              = map_form_field(fff, key, value, form_properties)
      - @api_namespace.non_primitive_properties.each_with_index do |property, index|
        = fields_for "data[non_primitive_properties_attributes][#{index}]", property do |ff|
          .form-group{class: "vr-#{ff.object.label} #{'disable-trix-file-attachment' unless ff.object.allow_attachments}"}
            = label_tag property.label
            = map_non_primitive_data_type(ff, property.field_type, form_properties)
            - if property.field_type == 'file'
              .mt-3
                %video{id: "#{property.label.parameterize.underscore}_preview_video", class: 'preview-media', controls: true, style: "display: none"}
                %img{id: "#{property.label.parameterize.underscore}_preview_img", class: 'preview-media', controls: true,  style: "display: none"}
          = ff.hidden_field :field_type
          = ff.hidden_field :label
          = ff.hidden_field :allow_attachments

    %div{id: "recaptcha_section_#{@api_form.object_id}"}
      - if @api_form.show_recaptcha || session[:recaptcha_v2_fallback]
        = recaptcha_tags callback: "ctaSuccessHandler_#{@api_form.object_id}", noscript: false
      - elsif @api_form.show_recaptcha_v3
        -# Hiding the recaptch v3 badge.
        -# reference: https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed
        :css
          .grecaptcha-badge {
            visibility: hidden;
          }

        %div{ style: "font-size: small;" }
          * This site is protected by Google
          = link_to 'reCAPTCHA.', 'https://www.google.com/recaptcha/about/', target: '_blank'
          By submitting this form, you agree to Google's
          = link_to 'Privacy Policy', 'https://policies.google.com/privacy', target: '_blank'
          and
          = link_to 'Terms of Service.', 'https://policies.google.com/terms', target: '_blank'

        = recaptcha_v3(callback: "ctaSuccessHandlerRecaptchaV3_#{@api_form.object_id}", action: sanitize_recaptcha_action_name("#{@api_namespace.name}_#{@api_form.object_id}"), site_key: ENV['RECAPTCHA_SITE_KEY_V3'], turbolinks: true)
      
    = f.submit @api_form.submit_button_label, disabled: @api_form.show_recaptcha || @api_form.show_recaptcha_v3, class: 'my-2 btn btn-primary', data: {disable_with: false}

- else 
  %h3.text-danger{ style: "font-size: small;" }
    * No recaptcha keys are defined. Please set the required keys or unselect recaptcha option for this form.

= render 'comfy/admin/api_namespaces/richtext_form_validations'

:javascript
  $(document).ready( function() {
    $('.array_select').each(function() {
      $(this).select2({
        multiple: true,
        required: true,
        placeholder: $(this).attr('placeholder'),
        tags: $(this).attr('data-tags')
      })
      $(this).val(JSON.parse($(this).attr('default_value'))).change();
    });
  });

- if @api_form.show_recaptcha || session[:recaptcha_v2_fallback]
  :javascript
    window.ctaSuccessHandler_#{@api_form.object_id} = function () {
      enableForm("#api_form_#{@api_form.object_id}");
    }

- if @api_form.show_recaptcha_v3
  :javascript
    window.ctaSuccessHandlerRecaptchaV3_#{@api_form.object_id} = function(elemId, token) {
      enableForm("#api_form_#{@api_form.object_id}");

      const element = document.getElementById(elemId);
      element.value = token;
    }

- execute_actions(@api_namespace, 'new_api_actions')

app/views/comfy/admin/api_forms/edit.html.haml
%h1 Editing api_form

= render 'form'

.mt-4
  = link_to 'Back', @api_namespace