config/routes.rb
require 'sidekiq/web'
class SubdomainConstraint
  def self.matches?(request)
    # plug in exclusions model here
    restricted_subdomains = []
    !restricted_subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  get 'cookies', to: 'cookies#index'
  get 'cookies/fetch', to: 'cookies#fetch'
  # analytics dashboard
  get 'dashboard', controller: 'comfy/admin/dashboard'
  get 'dashboard/sessions/:ahoy_visit_id', to: 'comfy/admin/dashboard#visit', as: :dashboard_visits
  get 'dashboard/events/:ahoy_event_type', to: 'comfy/admin/dashboard#events_detail', as: :dashboard_events
  get 'dashboard/events_list', to: 'comfy/admin/dashboard#events_list', as: :dashboard_events_list
  delete 'dashboard/events/:ahoy_event_type/destroy_event', to: 'comfy/admin/dashboard#destroy_event', as: :dashboard_destroy_event
  delete 'dashboard/events/:ahoy_event_type/destroy_visits', to: 'comfy/admin/dashboard#destroy_visits', as: :dashboard_destroy_visits

  post 'import_api_namespace', to: 'comfy/admin/api_namespaces#import_as_json', as: :import_as_json_api_namespaces

  get 'v2/dashboard', to: 'comfy/admin/v2/dashboard#dashboard'

  get 'sales_collateral_dashboard', to: 'comfy/admin/sales_collateral#dashboard'

  resources :sales_collateral, controller: 'comfy/admin/sales_collateral' do
    member do
      get 'export'
    end
  end

  # video calling, lock down new/create actions-- and allow public show action
  get 'rooms', to: 'comfy/admin/rooms#new'
  post 'rooms', to: 'comfy/admin/rooms#create'
  resources :rooms, only: [:show]
  
  resources :signup_wizard
  resources :signin_wizard
  constraints SubdomainConstraint do
    devise_for :users, controllers: {
      confirmations: 'users/confirmations',
      #omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks',
      invitations: 'users/invitations'
    }
  end

  resource :mailbox, only: [:show], controller: 'mailbox/mailbox' do
    resources :message_threads, controller: 'mailbox/message_threads' do
      resources :messages
      member do
        post 'send_message'
        patch 'add_categories'
      end
    end
    resources :email_templates, controller: 'mailbox/email_templates' do
      member do
        post 'test_send'
      end
    end
  end

  # email tracking
  get 'email_tracking/open', to: 'mailbox/tracking#open'

  # calendar / meetings functionality
  resources :calendars, controller: 'comfy/admin/calendars'
  resources :meetings

  resource :web_settings, controller: 'comfy/admin/web_settings', only: [:edit, :update]
  resources :users, controller: 'comfy/admin/users', as: :admin_users, except: [:create, :show] do
    collection do
      post 'invite'
    end
    member do
      get 'edit/sessions/:ahoy_visit_id', to: 'comfy/admin/dashboard#visit', as: :user_sessions_visit
    end
  end

  # api admin
  resources :api_namespaces, controller: 'comfy/admin/api_namespaces' do
    member do
      post 'duplicate_with_associations'
      post 'duplicate_without_associations'
      get 'export_with_associations_as_json'
      get 'export_without_associations_as_json'
      patch 'social_share_metadata'
      patch 'analytics_metadata'
      patch 'api_action_workflow'
      patch 'settings', to: 'comfy/admin/api_namespaces#update_settings'
    end

    resources :resources, except: [:index], controller: 'comfy/admin/api_resources'
    resources :api_clients, controller: 'comfy/admin/api_clients'
    resources :external_api_clients, controller: 'comfy/admin/external_api_clients' do
      member do
        get 'start'
        get 'stop'
        get 'clear_errors'
        get 'clear_state'
      end
    end
    resources :api_forms, controller: 'comfy/admin/api_forms', only: [:edit, :update]

    resources :resource, controller: 'resource', only: [:create]

    resources :api_actions, controller: 'comfy/admin/api_actions', only: [:index, :show, :new] do
      collection do
        get 'action_workflow'
      end
    end

    member do
      post 'discard_failed_api_actions'
      post 'rerun_failed_api_actions'
      get 'export'
      get 'export_api_resources'
    end
  end

  resources :api_keys, controller: 'comfy/admin/api_keys'
  resources :non_primitive_properties, controller: 'comfy/admin/non_primitive_properties', only: [:new]

  # system admin panel login
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_global_admin_session
    get 'otp/', to: 'users/sessions#two_factor'
    delete 'global_login', to: 'users/sessions#destroy'
    get 'resend_otp', to: "users/registrations#resend_otp"
    get '/users/sign_in/otp' => 'users/otp/sessions#new'
    post '/users/sign_in/otp' => 'users/otp/sessions#create'
  end
  # system admin panel authentication (ensure public schema as well)
  get 'sysadmin', to: 'admin/subdomain_requests#index'
  namespace :admin do
    authenticate :user, lambda { |u| u.global_admin? } do
      mount Sidekiq::Web => '/sidekiq'
      mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
      get 'web_console', to: 'web_console#index'
      mount Blazer::Engine, at: "blazer"
    end
    resources :subdomain_requests, except: [:new, :create] do
      member do
        get 'approve'
        get 'disapprove'
      end
    end
    resources :subdomains
  end

  
  namespace 'api' do
    get '/resources', to: 'resources#index', as: :show_resources
    scope ':version' do
      scope ':api_namespace' do
        get '/', to: 'resource#index'
        get '/show/:api_resource_id', to: 'resource#show', as: :show_resource
        get '/describe', to: 'resource#describe'
        post '/query', to: 'resource#query'
        post '/', to: 'resource#create', as: :create_resource
        patch '/edit/:api_resource_id', to: 'resource#update', as: :update_resource
        delete '/destroy/:api_resource_id', to: 'resource#destroy', as: :destroy_resource
        post '/:external_api_client/webhook', to: 'external_api_clients#webhook', as: :external_api_client_webhook
      end
    end
  end

  # ahoy analytics
  mount Ahoy::Engine => "/ahoy", as: :my_ahoy

  # to query CMS pages
  post '/query', to: 'search#query'
  # to query the rest of the system
  post "/graphql", to: "graphql#execute"

  # catch web client route before it gets hijacked by the server
  if RUBY_VERSION != "3.0.0"
    mount_ember_app :client, to: "/app"
  end

  comfy_route :cms_admin, path: "/admin"
  comfy_route :blog, path: "blog"
  comfy_route :blog_admin, path: "admin"
  mount SimpleDiscussion::Engine => "/forum"
  # cms comes last because its a catch all
  comfy_route :cms, path: "/"

  root to: 'content#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/email_template.rb
class EmailTemplate < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true

  SYMBOL_CAPTURE_PATTERN = /(?<=\{\{)[a-z]+(?:\.[a-z]+)*(?=\}\})/

  def dynamic_segments
    html_doc = Base64.decode64(self.html)
    html_doc.scan(SYMBOL_CAPTURE_PATTERN)
  end

  def inject_dynamic_segments(properties_obj = {})
  # pass a hash of properties or a API Resource instance and get dynamic HTML
  # usage option 1: EmailTemplate.last.inject_dynamic_segments({name: 'hideo kojima', link: "https://mgs.snake"})
  # usage option 2: EmailTemplate.last.inject_dynamic_segments(ApiResource.last)
  # works by extracting any variable defined between: {{}} 
  # example of including a variable called 'name': {{name}}
    
    html_doc = Base64.decode64(self.html)
    symbols = self.dynamic_segments
    symbol_mapping = ActiveSupport::HashWithIndifferentAccess.new
    output = html_doc

    if properties_obj.class == ApiResource
      api_resource = properties_obj
      symbols.each do |symbol|
        symbol_mapping[symbol] = api_resource.properties[symbol]
      end
    elsif properties_obj.class == Hash || properties_obj.class == ActiveSupport::HashWithIndifferentAccess
      symbols.each do |symbol|
        symbol_mapping[symbol] = properties_obj.with_indifferent_access[symbol]
      end
    else
      raise "dynamic segment mapping for Email Template is unrecognized. Please pass a hash of properties or API Resource instance"
    end
    
    symbols.each do |symbol|
      mapped_value = symbol_mapping[symbol]
      raise "dynamic segment token has no value, please ensure a value is provided" if mapped_value.nil? || mapped_value.empty?
      output = output.gsub("{{#{symbol}}}", mapped_value)
    end
    return output
  end
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord

end

app/controllers/mailbox/base_controller.rb
class Mailbox::BaseController < Comfy::Admin::Cms::BaseController
  before_action :check_email_authorization

  def check_email_authorization
    unless current_user.can_manage_email
      flash.alert = 'You do not have permission to manage email'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/mailbox/email_templates_controller.rb
class Mailbox::EmailTemplatesController < Mailbox::BaseController

  def index
    @email_templates = EmailTemplate.all
  end

  def new
  end

  def show
  end

  def create
    html_doc = params[:htmldoc]
    re_doc = params[:redoc]
    name = params[:name]
    
    email_template = EmailTemplate.create!(html: html_doc, template: re_doc, name: name)

    render json: { id: email_template.id }
  end

  def edit
    @email_template = EmailTemplate.find(params[:id])
  end

  def update
    email_template = EmailTemplate.find(params[:id])
    html_doc = params[:htmldoc]
    re_doc = params[:redoc]
    name = params[:name]
    email_template.update!(html: html_doc, template: re_doc, name: name)

    render json: { id: email_template.id }
  end

  def test_send
    email_template = EmailTemplate.find(params[:id])
    dynamic_segments = email_template.dynamic_segments
    symbol_mapping = ActiveSupport::HashWithIndifferentAccess.new
    dynamic_segments.each do |segment|
      symbol_mapping[segment] = params[segment]
    end

    email_body = email_template.inject_dynamic_segments(symbol_mapping)
    from_address = "#{Apartment::Tenant.current}@#{ENV['APP_HOST']}"
    email_subject = "#{email_template.name} test email"
    email_thread = MessageThread.create!(recipients: [current_user.email], subject: email_subject)
    email_body.encode!('UTF-16', 'UTF-8', :invalid => :replace, :replace => '')
    email_body.encode!('UTF-8', 'UTF-16')
    email_message = email_thread.messages.create!(
      content: email_body,
      from: from_address
    )
    EMailer.with(message: email_message, message_thread: email_thread).ship.deliver_later

    flash.notice = "Template test email sent to #{current_user.email}"
    redirect_to edit_mailbox_email_template_path(email_template.id)
  end

  def destroy
    email_template = EmailTemplate.find(params[:id])
    flash.notice = "#{email_template.name} destroyed!"
    email_template.destroy!
    redirect_to mailbox_email_templates_path
  end
end

app/controllers/mailbox/mailbox_controller.rb
class Mailbox::MailboxController < Mailbox::BaseController
  def show
    params[:q] ||= {}
    @message_threads_q = if params[:categories].present?
      MessageThread.joins(:messages).includes(:categories).for_category(params[:categories]).all.includes(:messages).ransack(params[:q])
    else
      MessageThread.joins(:messages).includes(:messages).ransack(params[:q])
    end

    @message_threads_q.sorts = ['messages_created_at desc', 'unread DESC NULLS LAST', 'created_at desc'] if @message_threads_q.sorts.empty?

    @message_threads = @message_threads_q.result(distinct: true).paginate(page: params[:page], per_page: params[:per_page] || 10)
  end
end

app/controllers/mailbox/message_threads_controller.rb
class Mailbox::MessageThreadsController < Mailbox::BaseController
  before_action :track_ahoy_visit, only: %i[show], raise: false
  before_action :load_thread, except: [:new, :create]

  def show
    if @message_thread.unread then @message_thread.update(unread: false) end
    ahoy.track(
      "subdomain-email-visit",
      {visit_id: current_visit.id, message_thread_id: @message_thread.id, user_id: current_user.id}
    ) if tracking_enabled? & current_visit
  end

  def new
    @message_thread = MessageThread.new
  end

  def create
    # remove empty string (a side-effect of rails select fields)
    params[:message_thread][:recipients].delete("")
    @message_thread = MessageThread.new(message_thread_params)
    @message = Message.new(message_params[:message].merge!(message_thread: @message_thread))
    if @message_thread.save && @message.save
      flash.notice = "Sent to #{@message_thread.recipients.join(', ')}"
      redirect_to mailbox_message_thread_path(id: @message_thread.id)
    else
      flash.alert = "errors: #{@message_thread.errors.full_messages.to_sentence}  #{@message.errors.full_messages.to_sentence}"
      if @message_thread.persisted?
        redirect_to mailbox_message_thread_path(id: @message_thread.id)
      else
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def send_message
    @message = Message.new(message_params[:message].merge!(message_thread: @message_thread))
    if @message.save
      flash.notice = "Sent to #{@message_thread.recipients.join(', ')}"
    else
      flash.alert = @message.errors.full_messages.to_sentence
    end
    redirect_back(fallback_location: mailbox_message_thread_path(id: @message_thread.id))
  end

  def destroy
    if @message_thread.destroy
      flash.notice = 'Email thread deleted!'
    else
      flash.alert = 'Email thread could not be deleted. Please try again later'
    end
    redirect_to mailbox_path
  end

  def add_categories
    @message_thread.update(add_categories_params)
    redirect_to mailbox_path
  end

  private
  def message_params
    params.require(:message_thread).permit(
      message: [
        :content
      ]
    )
  end

  def message_thread_params
    params.require(:message_thread).permit(
      :subject,
      recipients: [],
      category_ids: [],
    )
  end

  def add_categories_params
    params.require(:message_thread).permit(category_ids: [])
  end

  def load_thread
    @message_thread = MessageThread.find_by(id: params[:id])
    unless @message_thread
      flash.alert = 'Could not find thread'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/mailbox/tracking_controller.rb
class Mailbox::TrackingController < ApplicationController
  def open
    emails = params[:emails]
    message_id = params[:message_id]
    email_uuid = params[:email_uuid]
    message = Message.find_by(id: message_id, email_message_id: email_uuid)
    ip = request.ip
    user_agent = request.user_agent

    if message
      message.update(opened: true)
      # mark as opened
    end

    render json: { status: 200, code: 'OK' }
  end
end

app/views/mailbox/email_templates/edit.html.haml
.page-header
  .h2
    = link_to 'Email Templates', mailbox_email_templates_path
.container.my-2
  = label_tag "name"
  = text_field_tag "name", @email_template.name, id: 'email_template_name'
.container.my-2
  = label_tag "Slug: "
  = @email_template.slug
.container.my-2
  = label_tag "Dynamic segments ( defined as {{}} ): "
  = @email_template.dynamic_segments.join(', ')
.container.my-2
  = label_tag "Test send: "
  = form_tag(test_send_mailbox_email_template_path(@email_template.id), method: "POST", class: 'form-group') do
    - @email_template.dynamic_segments.each do |segment|
      = label_tag(segment.to_sym, "#{segment}:")
      = text_field_tag(segment.to_sym, nil, class: 'form-control', required: true)
    = submit_tag("Email me this template!", class: 'btn btn-secondary my-2')
.container.my-2
  = label_tag "Copy HTML: "
  = button_tag "Copy to clipboard", id: 'copyRevolvHtml' 

.container
  #VioletEmailEditor

  %button#VioletEmailEditorSubmit.btn.btn-primary.my-2
    = "Save"
  = link_to "Delete", mailbox_email_template_path(@email_template.id), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }
    
:javascript
  let template = "#{escape_javascript(@email_template.template)}"
  let id = "#{@email_template.id}"
  const app = Revolvapp('#VioletEmailEditor', {
    editor: {
      path: '/revolvapp-2-3-10/',   
    },
    content: template
  });

  $('#copyRevolvHtml').click(function() {
    let htmldoc = app.editor.getHtml()

    navigator.clipboard.writeText(htmldoc);

    // Alert the copied text
    alert("Copied html");
  });

  $('#VioletEmailEditorSubmit').click(function() {
    $("#VioletEmailEditorSubmit").prop("disabled", true)
    let authenticityToken = $('meta[name="csrf-token"]').attr('content');

    let htmldoc = app.editor.getHtml()
    let redoc = app.editor.getTemplate(true)
    let name = $('#email_template_name').val()
    const endpoint = "#{mailbox_email_template_path}"

    if (name && htmldoc) {
      $.ajax({
        url: endpoint,
        type: 'PATCH',
        headers: {
            'X-CSRF-Token': authenticityToken
        },
        data: JSON.stringify({ htmldoc: btoa(htmldoc), redoc: redoc, name: name, id: id }),
        contentType: "application/json; charset=utf-8",
        success: function(response) {
          window.location.href = `${endpoint}/${response.id}/edit`
          window.location.reload()
        }
      });
    } else {
      window.alert('Please give your template a name and set its content')
    }

    $("#VioletEmailEditorSubmit").prop("disabled", false)
  });

app/views/mailbox/email_templates/index.html.haml
.page-header
  = link_to 'New Email Template', new_mailbox_email_template_path, class: 'btn btn-secondary float-right mx-1'
  %h2 
    = link_to "Email", mailbox_path 
    Templates
%ol
  - @email_templates.each do |email_template|
    %li
      = link_to email_template.name, edit_mailbox_email_template_path(email_template.id)

app/views/mailbox/email_templates/new.html.haml
.page-header
  .h2
    = 'Email Templates'
  .container.m-2
    .h3
      = "Docs:"
    %a{href: "https://imperavi.com/legacy/revolvapp/docs/syntax/tags/", target: '_blank'}
      Imperavi Revolvapp
  .container.m-2
    .h3
      = "AI prompt:"
    .p
      = "this is re-html, used by revolvapp,"
    .p
      = "... copy pasted editor code"
    .p
      = "using the above markup language create me a..."
.container.my-2
  = label_tag "name"
  = text_field_tag "name", nil, id: 'email_template_name'

.container
  #VioletEmailEditor

%button#VioletEmailEditorSubmit.btn.btn-primary.my-2
  = "Save"

:javascript
  const app = Revolvapp('#VioletEmailEditor', {
    editor: {
      path: '/revolvapp-2-3-10/',
      template: '/revolvapp-2-3-10/templates/index.html',
    }
  });

  $('#VioletEmailEditorSubmit').click(function() {
    $("#VioletEmailEditorSubmit").prop("disabled", true)
    let authenticityToken = $('meta[name="csrf-token"]').attr('content');

    let htmldoc = app.editor.getHtml()
    let redoc = app.editor.getTemplate(true)
    let name = $('#email_template_name').val()
    const endpoint = "#{mailbox_email_templates_path}"
    if (name && htmldoc) {
      $.ajax({
        url: endpoint,
        type: 'POST',
        headers: {
            'X-CSRF-Token': authenticityToken
        },
        data: JSON.stringify({ htmldoc: btoa(htmldoc), redoc: redoc, name: name }),
        contentType: "application/json; charset=utf-8",
        success: function(response) {
          window.location.href = `${endpoint}/${response.id}/edit`
        }
      });
    } else {
      window.alert('Please give your template a name and set its content')
    }

    $("#VioletEmailEditorSubmit").prop("disabled", false)
  });